#####################################################
# amlogic video decoder firmware
####################################################
LOCAL_PATH := $(call my-dir)
ifeq ($(shell test $(PLATFORM_SDK_VERSION) -ge 26 && echo OK),OK)
OUT_PATH := $(TARGET_OUT_VENDOR)
else
OUT_PATH := $(TARGET_OUT)/
endif


include $(CLEAR_VARS)
LOCAL_MODULE := libtee_load_video_fw
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB := both
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH_64 := $(OUT_PATH)/lib64/
LOCAL_MODULE_PATH_32 := $(OUT_PATH)/lib/
LOCAL_SRC_FILES_arm :=  lib/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_SRC_FILES_arm64 := lib64/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_STRIP_MODULE := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := tee_preload_fw
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH_64 := $(OUT_PATH)/bin
LOCAL_MODULE_PATH_32 := $(OUT_PATH)/bin
LOCAL_SRC_FILES_arm := lib/$(LOCAL_MODULE)
LOCAL_SRC_FILES_arm64 := lib64/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := 526fc4fc-7ee6-4a12-96e3-83da9565bce8
LOCAL_MULTILIB := both
LOCAL_MODULE_SUFFIX := .ta
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH_64 := $(OUT_PATH)/lib/teetz
LOCAL_MODULE_PATH_32 := $(OUT_PATH)/lib/teetz
LOCAL_SRC_FILES_arm :=  lib/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_SRC_FILES_arm64 := lib64/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_STRIP_MODULE := false
include $(BUILD_PREBUILT)

